"""add rounds played column

Revision ID: c35d06d50b68
Revises: 3dea1a87672e
Create Date: 2021-05-24 15:10:30.031000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c35d06d50b68'
down_revision = '3dea1a87672e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_score', sa.Column('rounds_played', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match_score', 'rounds_played')
    # ### end Alembic commands ###
